- name: Hello World Sample
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! doing a demo"
    - name: Get a random amount of time
      set_fact:
        random_number: "{{ 40 | random }}"
      run_once: yes
    - name: Pause for a min amount of time
      pause:
        seconds: 6
    - name: Pause for a random amount of seconds
      pause:
        seconds: "{{ random_number }}"
    - name: 1 Pause for a random amount of seconds
      pause:
        seconds: "{{ random_number }}"
    - name: 2 Pause for a random amount of seconds
      pause:
        seconds: "{{ random_number }}"
    - name: 3 Pause for a random amount of seconds
      pause:
        seconds: "{{ random_number }}"
    - name: Closing job
      debug:
        msg: "Demo job complete"
